Name: Product
Host: 0.0.0.0
Port: 8001

ProductRpc:
  Etcd:
    Hosts:
      - localhost:2379
    Key: product.rpc

Mysql:
  DataSource: root:123456@tcp(127.0.0.1:3306)/mall?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai

CacheRedis:
  - Host: 127.0.0.1:6379
    Pass: "123456"
    Type: node

Auth:
  AccessSecret: uOvKLmVfz3vesDNYd4Z0I1SiT7MweJhl
  AccessExpire: 86400

